apiVersion: v1
kind: Service
metadata:
  name: mcp-agentic-framework-lb
  namespace: default
spec:
  selector:
    app: mcp-agentic-framework
  ports:
  - port: 3113
    targetPort: 3113
    protocol: TCP
    name: http
  type: LoadBalancer